### PR TITLE
Update to embedded-hal v2 traits and stop using mem::uninitialized

### PR DESCRIPTION
**Pull request by e-matteson**
This will become version 0.2.0 of the `keypad` crate.

## Breaking Changes:
- It now uses v2 of the embedded-hal's `InputPin` and `OutputPin` traits, which have an associated error type and whose methods can fail. 
- The `keypad_struct` macro now requires users to supply an error type.

## Non-breaking changes
- The deprecated `mem::uninitialized` is replaced by `mem::MaybeUninit` (#3).
- The crate is updated to 2018 edition.
- The crate no longer requires nightly (tested with stable rustc 1.63).

### CODE REVIEW

**Comment by ghost** [comment]
offhand it looks fine, but it would be good to get this crate tested using https://github.com/rust-lang/miri to ensure no more issues are introduced.

(I tested it locally, and it passes, so at least given the tests that exist, it doesn't create uninit data anymore)

**Comment by barafael** [comment]
Nice! Any reason this isn't on `edition = 2021`?

**Comment by e-matteson** [comment]
> Any reason this isn't on edition = 2021?

I was thinking I'd avoid increasing the minimum supported rust version. But it turns out using the 2021 edition will only bump it from 1.55 to 1.56, so that's worthwhile. Done.

> offhand it looks fine, but it would be good to get this crate tested using https://github.com/rust-lang/miri to ensure no more issues are introduced.

I used miri to run the code with a few different array sizes and it didn't notice any problems. Is there anything else specific you recommend I do/test?

**Comment by ghost** [comment]
Nothing in particular jumps out as suspicious, I would have suggested putting it in CI but it's probably not worth setting up CI just for miri here.

**Comment by e-matteson** [comment]
Tested on real hardware, merging. Thank you both for your help.

**Pull request merged**
